apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f3izz3ww1-java-quarkus
  janus-idp.io/tekton: f3izz3ww1-java-quarkus
  backstage.io/kubernetes-id: f3izz3ww1-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: f3izz3ww1-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
